version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gestion_postgres
    environment:
      POSTGRES_DB: gestion_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gestion_network

volumes:
  postgres_data:

networks:
  gestion_network:
    driver: bridge